example:
    baseUrl: http://localhost:8080
server:
    port: 8081
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: <clientID>
            client-secret: <clientSecret>
            scope: openid profile custom_mod
            
        provider:
          okta:
            authorization-uri: https://<oktaurl>.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://<oktaurl>.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://<oktaurl>.oktapreview.com/oauth2/default/v1/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://<oktaurl>.oktapreview.com/oauth2/default/v1/keys
